server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pract_8th_user-service
    username: postgres
    password: bondalovskiy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/