server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pract_8th_product-service
    username: postgres
    password: bondalovskiy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bndlvsk.orderservice.event"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  tokenPrefix: "Bearer "

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Kafka topic names
kafka:
  topic:
    order-created: pizza-order-created
    order-updated: pizza-order-updated
    order-deleted: pizza-order-deleted